import {
  Box,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Flex,
  SimpleGrid,
  Heading,
  Button,
  ButtonGroup,
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";
import { AddIcon } from "@chakra-ui/icons";

function App() {
  return (
    <>
      <SimpleGrid gap={5} columns={1}>
        <Box>
          <Table>
            <Thead>
              <Tr>
                <Th>Lorem.</Th>
                <Th>Illum!</Th>
                <Th>Commodi.</Th>
                <Th>Inventore.</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Natus?</Td>
                <Td>Porro!</Td>
                <Td>Expedita?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Itaque?</Td>
                <Td>Dignissimos?</Td>
                <Td>Commodi?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Odio?</Td>
                <Td>Possimus!</Td>
                <Td>Esse.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Quae.</Td>
                <Td>Error.</Td>
                <Td>Accusamus?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Cum.</Td>
                <Td>Dolores?</Td>
                <Td>Magnam.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Voluptatem!</Td>
                <Td>Eum!</Td>
                <Td>Impedit?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Laboriosam.</Td>
                <Td>Quidem!</Td>
                <Td>Error.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Veritatis?</Td>
                <Td>Cum?</Td>
                <Td>Tempore!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Quo?</Td>
                <Td>Alias!</Td>
                <Td>Explicabo.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Aliquam.</Td>
                <Td>Alias.</Td>
                <Td>Quidem?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Earum.</Td>
                <Td>Adipisci!</Td>
                <Td>Eius.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Quis.</Td>
                <Td>Dolor.</Td>
                <Td>Accusantium.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Eos.</Td>
                <Td>Assumenda.</Td>
                <Td>Est?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Odio.</Td>
                <Td>Consequuntur?</Td>
                <Td>In.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Tempore.</Td>
                <Td>Ea.</Td>
                <Td>Praesentium!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Ipsam.</Td>
                <Td>Dicta?</Td>
                <Td>Aperiam!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Nostrum.</Td>
                <Td>Labore?</Td>
                <Td>Et!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Officia!</Td>
                <Td>Dicta?</Td>
                <Td>Cum.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Totam?</Td>
                <Td>Aliquam?</Td>
                <Td>Atque!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Neque.</Td>
                <Td>Culpa?</Td>
                <Td>Dignissimos?</Td>
              </Tr>
            </Tbody>
          </Table>
        </Box>
      </SimpleGrid>
    </>
  );
}

export default App;
